/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Feb 23 20:46:53 2019. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Testing_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Testing, wearout_count, wearout_count, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
